import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { SUPPORTED_LANGUAGES, setLanguage } from '../i18n';
import { Layout, Menu, Avatar, Dropdown, Typography, Badge } from 'antd';
import { DashboardOutlined, BarChartOutlined, LogoutOutlined, UserOutlined, TeamOutlined, SmileOutlined, ReadOutlined, ContactsOutlined, NotificationOutlined, CalendarOutlined, BarsOutlined, MessageOutlined, CoffeeOutlined, ScheduleOutlined, CarOutlined, GiftOutlined, SolutionOutlined, WalletOutlined, SettingOutlined, BgColorsOutlined, CrownOutlined, BellOutlined, FileProtectOutlined, PictureOutlined, RocketOutlined, HistoryOutlined, CustomerServiceOutlined } from '@ant-design/icons';
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import { onValue, ref } from 'firebase/database';
import { useAuth } from '../context/AuthContext';
import { THEME } from '../theme';
import { useUnreadMessagesCount } from '../utils/messageHelpers';
import { database } from '../config/firebase';
import NotificationToasts from './NotificationToasts';

const { Header, Sider, Content } = Layout; const { Text } = Typography;
function groupLabel(text){return <span style={{fontSize:10.5,fontWeight:800,letterSpacing:'0.09em',textTransform:'uppercase',color:'#B3AFCB'}}>{text}</span>}
function coloredIcon(Icon,color){return <span style={{width:24,height:24,borderRadius:7,background:`${color}1F`,color,display:'inline-flex',alignItems:'center',justifyContent:'center',fontSize:13,flexShrink:0}}><Icon/></span>}
function buildMenuItems(t,unreadCount,supportUnread){return [
 {key:'grp-genel',type:'group',label:groupLabel(t('navigation.general')),children:[{key:'/',icon:coloredIcon(DashboardOutlined,THEME.primary),label:t('navigation.dashboard')},{key:'/istatistik',icon:coloredIcon(BarChartOutlined,THEME.blue),label:t('navigation.statistics')}]},
 {key:'grp-kurum',type:'group',label:groupLabel(t('navigation.institutionManagement')),children:[{key:'/siniflar',icon:coloredIcon(ReadOutlined,THEME.blue),label:t('navigation.classes')},{key:'/toplu-kurulum',icon:coloredIcon(RocketOutlined,THEME.green),label:t('navigation.bulkSetup')},{key:'/cocuklar',icon:coloredIcon(SmileOutlined,THEME.orange),label:t('navigation.children')},{key:'/yoneticiler',icon:coloredIcon(CrownOutlined,THEME.gold),label:t('navigation.administrators')},{key:'/ogretmenler',icon:coloredIcon(TeamOutlined,THEME.primary),label:t('navigation.teachers')},{key:'/veliler',icon:coloredIcon(ContactsOutlined,THEME.green),label:t('navigation.parents')}]},
 {key:'grp-iletisim',type:'group',label:groupLabel(t('navigation.communication')),children:[{key:'/duyurular',icon:coloredIcon(NotificationOutlined,THEME.red),label:t('navigation.announcements')},{key:'/etkinlikler',icon:coloredIcon(CalendarOutlined,THEME.teal),label:t('navigation.events')},{key:'/galeri',icon:coloredIcon(PictureOutlined,THEME.orange),label:t('navigation.gallery')},{key:'/anketler',icon:coloredIcon(BarsOutlined,THEME.purple),label:t('navigation.polls')},{key:'/mesajlar',icon:coloredIcon(MessageOutlined,THEME.blue),label:unreadCount>0?<span>{t('navigation.messages')} <Badge count={unreadCount} size="small" style={{marginLeft:4}}/></span> :t('navigation.messages')},{key:'/destek',icon:coloredIcon(CustomerServiceOutlined,THEME.red),label:supportUnread>0?<span>{t('navigation.support')} <Badge count={supportUnread} size="small" style={{marginLeft:4}}/></span> :t('navigation.support')}]},
 {key:'grp-operasyon',type:'group',label:groupLabel(t('navigation.dailyOperations')),children:[{key:'/yemek-listesi',icon:coloredIcon(CoffeeOutlined,THEME.orange),label:t('navigation.meals')},{key:'/ders-programi',icon:coloredIcon(ScheduleOutlined,THEME.teal),label:t('navigation.schedule')},{key:'/nobet-cizelgesi',icon:coloredIcon(SolutionOutlined,THEME.gold),label:t('navigation.dutyRoster')},{key:'/personel-gorevleri',icon:coloredIcon(SolutionOutlined,THEME.primary),label:t('navigation.staffTasks')},{key:'/servis',icon:coloredIcon(CarOutlined,THEME.blue),label:t('navigation.service')},{key:'/dogum-gunleri',icon:coloredIcon(GiftOutlined,THEME.gold),label:t('navigation.birthdays')},{key:'/odemeler',icon:coloredIcon(WalletOutlined,THEME.green),label:t('navigation.payments')}]},
 {key:'grp-ayarlar',type:'group',label:groupLabel(t('navigation.settings')),children:[{key:'/ayarlar/kurum',icon:coloredIcon(SettingOutlined,THEME.muted),label:t('navigation.institutionInfo')},{key:'/ayarlar/tema',icon:coloredIcon(BgColorsOutlined,THEME.purple),label:t('navigation.theme')},{key:'/ayarlar/abonelik',icon:coloredIcon(CrownOutlined,THEME.gold),label:t('navigation.subscription')},{key:'/ayarlar/kurum-zili',icon:coloredIcon(BellOutlined,THEME.red),label:t('navigation.institutionBell')},{key:'/yasal-belgeler',icon:coloredIcon(FileProtectOutlined,THEME.blue),label:t('navigation.legalDocuments')},{key:'/denetim-kaydi',icon:coloredIcon(HistoryOutlined,THEME.muted),label:t('navigation.auditLog')}]}
]}
export default function PanelLayout(){const [collapsed,setCollapsed]=useState(false);const [supportUnread,setSupportUnread]=useState(0);const {kullanici,kres,cikisYap}=useAuth();const {t,i18n}=useTranslation();const navigate=useNavigate();const location=useLocation();const unreadCount=useUnreadMessagesCount(kullanici?.uid||kullanici?.id);const menuItems=buildMenuItems(t,unreadCount,supportUnread);const userId=kullanici?.id||kullanici?.uid||kullanici?.authUid||'';const kresId=kullanici?.kresId||kres?.id||'';
 useEffect(()=>{if(!kresId||!userId)return()=>{};const unsub=onValue(ref(database,'destekMesajlari'),snap=>{const rows=Object.values(snap.val()||{}).filter(x=>x&&x.kresId===kresId&&(x.userId===userId||x.senderRole==='superadmin'));const count=rows.filter(x=>x.durum==='yeni'&&Object.values(x.yanitlar||{}).some(r=>String(r?.authorRole||'').toLowerCase().includes('super'))).length;setSupportUnread(count);},()=>setSupportUnread(0));return()=>unsub();},[kresId,userId]);
 const userMenu={items:[{key:'cikis',icon:<LogoutOutlined/>,label:t('common.logout')}],onClick:async({key})=>{if(key==='cikis')await cikisYap();}};
 return <Layout style={{minHeight:'100vh'}}><NotificationToasts kullanici={kullanici}/><Sider collapsible collapsed={collapsed} onCollapse={setCollapsed} theme="light" width={236} style={{background:'linear-gradient(180deg, #FDFCFF 0%, #F7F3FF 100%)',borderRight:`1px solid ${THEME.border}`,display:'flex',flexDirection:'column'}}><div style={{height:64,display:'flex',alignItems:'center',justifyContent:collapsed?'center':'flex-start',gap:10,padding:collapsed?0:'0 20px'}}><img src="/logo.png" alt="Yumurcak Kreş" style={{width:38,height:38,borderRadius:'50%',flexShrink:0,boxShadow:'0 3px 10px rgba(76,41,156,0.22)'}}/>{!collapsed&&<Text strong style={{color:THEME.text,fontSize:18,letterSpacing:-0.2}}>Yumurcak</Text>}</div><div style={{flex:1,minHeight:0,overflowY:'auto',padding:'4px 10px 12px'}}><Menu mode="inline" selectedKeys={[location.pathname]} items={menuItems} onClick={({key})=>navigate(key)} style={{background:'transparent',border:'none'}}/></div><div style={{padding:12,borderTop:`1px solid ${THEME.border}`,flexShrink:0}}><Dropdown menu={userMenu} placement="topLeft"><div style={{display:'flex',alignItems:'center',gap:10,cursor:'pointer',padding:collapsed?'8px 0':'8px 10px',borderRadius:12,justifyContent:collapsed?'center':'flex-start'}}><Avatar size={32} icon={<UserOutlined/>} style={{background:THEME.primary,flexShrink:0}}/>{!collapsed&&<><div style={{lineHeight:1.2,minWidth:0,flex:1}}><Text strong style={{fontSize:12.5,display:'block',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{kullanici?.ad||kullanici?.kullaniciAdi||kullanici?.email||'Kullanıcı'}</Text><Text type="secondary" style={{fontSize:11}}>{kullanici?.rol==='yonetici'?t('common.administrator'):(kullanici?.rol||t('common.administrator'))}</Text></div><LogoutOutlined style={{color:'#C7C4DA',fontSize:14,flexShrink:0}}/></>}</div></Dropdown></div></Sider><Layout><Header style={{background:'rgba(255,255,255,0.82)',backdropFilter:'blur(10px)',WebkitBackdropFilter:'blur(10px)',padding:'0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',boxShadow:'0 2px 12px rgba(25,26,35,0.05)',position:'sticky',top:0,zIndex:2}}><div onClick={()=>navigate('/ayarlar/kurum')} style={{display:'flex',alignItems:'center',gap:12,cursor:'pointer',padding:'6px 14px 6px 6px',borderRadius:999}}><img src={kres?.logoUrl||'/logo.png'} alt={kres?.ad||kres?.isim||'Kurum'} style={{width:34,height:34,borderRadius:'50%',objectFit:'cover',border:`2px solid ${THEME.primarySoft}`}}/><div style={{lineHeight:1.15}}><Text strong style={{fontSize:17,letterSpacing:-0.2,display:'block'}}>{kres?.ad||kres?.isim||'Kreş'}</Text><Text type="secondary" style={{fontSize:11,fontWeight:600}}>{t('common.institutionProfile')}</Text></div></div><div style={{display:'flex',alignItems:'center',gap:8}}>
<Dropdown menu={{items:SUPPORTED_LANGUAGES.map((item)=>({key:item.code,label:<span>{item.flag} {item.label}</span>})),selectedKeys:[i18n.language],onClick:({key})=>setLanguage(key)}} placement="bottomRight"><div style={{display:'flex',alignItems:'center',gap:6,cursor:'pointer',padding:'7px 10px',borderRadius:10,border:`1px solid ${THEME.border}`,background:'#fff'}}><span>{SUPPORTED_LANGUAGES.find((x)=>x.code===i18n.language)?.flag||'🌐'}</span><Text style={{fontWeight:600,fontSize:12}}>{SUPPORTED_LANGUAGES.find((x)=>x.code===i18n.language)?.label||t('common.language')}</Text></div></Dropdown>
<Dropdown menu={userMenu} placement="bottomRight"><div style={{display:'flex',alignItems:'center',gap:10,cursor:'pointer',padding:'6px 12px 6px 6px',borderRadius:999}}><Avatar icon={<UserOutlined/>} style={{background:THEME.primary}}/><Text style={{fontWeight:600}}>{kullanici?.ad||kullanici?.kullaniciAdi||kullanici?.email}</Text></div></Dropdown>
</div></Header><Content style={{margin:24,background:THEME.card,padding:24,borderRadius:THEME.radius,boxShadow:THEME.shadow,border:`1px solid ${THEME.border}`}}><Outlet/></Content></Layout></Layout>;
}
